# _config.yml - Key sections to customize

# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Mun Hong Fong  # Change this to your full name
first_name: Mun Hong
middle_name: 
last_name: Fong
email: mf374 \[at\] duke \[dot\] edu 

description: > # Your site description (appears in search engines)
  Personal website of Your Name, CS PhD student at University Name.

footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: https://fongmunhong.github.io  # Important!
baseurl:  # Leave empty for user pages

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

github_username: FongMunHong
twitter_username: mhfong1947
linkedin_username: mun-hong-fong-189a311a3
scholar_userid: 3XrxD-kAAAAJ